#!/usr/bin/env zsh

# necessary to run aliases in sudo
alias sudo="sudo "

alias vim="nvim"
alias mvim="nvim --cmd \"let g:MODE='minimal'\""
alias mpvim="nvim --cmd \"let g:MODE='min-plugins'\""
alias npvim="nvim --cmd \"let g:MODE='no-plugins'\""
alias el="eza -a"
alias ell="eza -la"
alias etree="eza --tree"
alias etrea="eza --tree -a"
alias lg="lazygit"
alias lgit="lazygit"
alias legit="lazygit"
alias bman="batman"
alias :q="exit"
alias r=". remember goto"
alias r1=". remember 1"
alias r2=". remember 2"
alias r3=". remember 3"
alias r4=". remember 4"
alias r5=". remember 5"
alias rem="remember"
alias remd="remember d"
